name: Random Teams

on:
  push:
    branches:
      - main

jobs:
  random-teams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Bash
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Run Random Teams Script
      id: random-teams
      run: |
        chmod +x random_teams.sh
        team_members_str=$(./random_teams.sh)
        echo "::set-output name=team_members_str::$team_members_str"

    - name: Use Team Members String
      run: |
        echo "Team Members:"
        echo "${{ steps.random-teams.outputs.team_members_str }}"
