name: Random Teams
on: 
  schedule:
    - cron: '0 22 * * 1-5'
    
jobs:
  random-teams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Bash
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Run Random Teams Script
      id: random-teams
      run: |
        chmod +x random_teams.sh
        team_members_str=$(./random_teams.sh)
        echo "::set-output name=team_members_str::$team_members_str"

    - name: Use Team Members String
      run: |
        echo "Team Members:"
        echo "${{ steps.random-teams.outputs.team_members_str }}"
        
    - name: Create Issue
      uses: dacbd/create-issue-action@v1.2.1
      with:
        # Your Github PAT, defaults to actions token
        token: ${{ secrets.TOKEN }}
        # Repo Owner, if not set implied by context.
        # owner: # optional
        # Repo or impiled by the current context
        # repo: # optional
        # Issue title
        title: 랜덤 조 배치 결과
        # Body content of issue
        body: ${{ steps.random-teams.outputs.team_members_str }}
        # Milestone associated with issue
        # milestone: # optional
        # CSV of labels (e.x. 'p0-critial,bug,aws')
        # labels: # optional
        # CSV of github usernames to assign (e.x. 'dacbd,nlf')
        # assignees: # optional
              
